/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tabelagrafica;

/**
 *
 * @author rodolfo
 */
public class JFramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jAba1 = new javax.swing.JTabbedPane();
        jPainelEntrada = new javax.swing.JPanel();
        jBotaoArquivo = new javax.swing.JButton();
        jTextoCaminhoArquivo = new javax.swing.JTextField();
        jBotaoSalvaTudo = new javax.swing.JButton();
        jPainel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jAreaTextoRol1 = new javax.swing.JTextArea();
        jBotaoExcluir1 = new javax.swing.JButton();
        jBotaoAlterar1 = new javax.swing.JButton();
        jBotaoAdicionar1 = new javax.swing.JButton();
        jTextoAdicionar1 = new javax.swing.JTextField();
        jPainel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jAreaTextoRol3 = new javax.swing.JTextArea();
        jBotaoExcluir2 = new javax.swing.JButton();
        jBotaoAlterar2 = new javax.swing.JButton();
        jBotaoAdicionar2 = new javax.swing.JButton();
        jTextoAdicionar2 = new javax.swing.JTextField();
        jAba2 = new javax.swing.JPanel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jAba1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jBotaoArquivo.setText("Arquivo");

        jBotaoSalvaTudo.setText("Salvar Tudo");

        jPainel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Rol 1"));

        jAreaTextoRol1.setColumns(20);
        jAreaTextoRol1.setRows(5);
        jScrollPane1.setViewportView(jAreaTextoRol1);

        jBotaoExcluir1.setText("Excluir");

        jBotaoAlterar1.setText("Alterar");

        jBotaoAdicionar1.setText("Adicionar");

        jTextoAdicionar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextoAdicionar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPainel1Layout = new javax.swing.GroupLayout(jPainel1);
        jPainel1.setLayout(jPainel1Layout);
        jPainel1Layout.setHorizontalGroup(
            jPainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPainel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPainel1Layout.createSequentialGroup()
                        .addGap(0, 344, Short.MAX_VALUE)
                        .addGroup(jPainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPainel1Layout.createSequentialGroup()
                                .addComponent(jBotaoAlterar1)
                                .addGap(18, 18, 18)
                                .addComponent(jBotaoExcluir1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPainel1Layout.createSequentialGroup()
                                .addComponent(jTextoAdicionar1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBotaoAdicionar1))))
                    .addComponent(jScrollPane1)))
        );
        jPainel1Layout.setVerticalGroup(
            jPainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPainel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotaoAdicionar1)
                    .addComponent(jTextoAdicionar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotaoExcluir1)
                    .addComponent(jBotaoAlterar1)))
        );

        jPainel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Rol 1"));

        jAreaTextoRol3.setColumns(20);
        jAreaTextoRol3.setRows(5);
        jScrollPane3.setViewportView(jAreaTextoRol3);

        jBotaoExcluir2.setText("Excluir");

        jBotaoAlterar2.setText("Alterar");

        jBotaoAdicionar2.setText("Adicionar");

        jTextoAdicionar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextoAdicionar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPainel2Layout = new javax.swing.GroupLayout(jPainel2);
        jPainel2.setLayout(jPainel2Layout);
        jPainel2Layout.setHorizontalGroup(
            jPainel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPainel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPainel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPainel2Layout.createSequentialGroup()
                        .addGap(0, 362, Short.MAX_VALUE)
                        .addGroup(jPainel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPainel2Layout.createSequentialGroup()
                                .addComponent(jBotaoAlterar2)
                                .addGap(18, 18, 18)
                                .addComponent(jBotaoExcluir2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPainel2Layout.createSequentialGroup()
                                .addComponent(jTextoAdicionar2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBotaoAdicionar2))))))
        );
        jPainel2Layout.setVerticalGroup(
            jPainel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPainel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPainel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotaoAdicionar2)
                    .addComponent(jTextoAdicionar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPainel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotaoExcluir2)
                    .addComponent(jBotaoAlterar2)))
        );

        javax.swing.GroupLayout jPainelEntradaLayout = new javax.swing.GroupLayout(jPainelEntrada);
        jPainelEntrada.setLayout(jPainelEntradaLayout);
        jPainelEntradaLayout.setHorizontalGroup(
            jPainelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPainelEntradaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPainelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPainelEntradaLayout.createSequentialGroup()
                        .addComponent(jBotaoArquivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBotaoSalvaTudo)
                        .addGap(93, 93, 93))
                    .addGroup(jPainelEntradaLayout.createSequentialGroup()
                        .addGroup(jPainelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextoCaminhoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPainel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(30, Short.MAX_VALUE))))
            .addGroup(jPainelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPainelEntradaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPainel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPainelEntradaLayout.setVerticalGroup(
            jPainelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPainelEntradaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPainelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotaoArquivo)
                    .addComponent(jBotaoSalvaTudo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextoCaminhoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                .addComponent(jPainel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(jPainelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPainelEntradaLayout.createSequentialGroup()
                    .addGap(78, 78, 78)
                    .addComponent(jPainel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(233, Short.MAX_VALUE)))
        );

        jAba1.addTab("Entrada de dados", jPainelEntrada);

        jAba2.setEnabled(false);

        javax.swing.GroupLayout jAba2Layout = new javax.swing.GroupLayout(jAba2);
        jAba2.setLayout(jAba2Layout);
        jAba2Layout.setHorizontalGroup(
            jAba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 783, Short.MAX_VALUE)
        );
        jAba2Layout.setVerticalGroup(
            jAba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
        );

        jAba1.addTab("Aba2", jAba2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAba1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAba1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextoAdicionar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextoAdicionar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextoAdicionar2ActionPerformed

    private void jTextoAdicionar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextoAdicionar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextoAdicionar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jAba1;
    private javax.swing.JPanel jAba2;
    private javax.swing.JTextArea jAreaTextoRol1;
    private javax.swing.JTextArea jAreaTextoRol3;
    private javax.swing.JButton jBotaoAdicionar1;
    private javax.swing.JButton jBotaoAdicionar2;
    private javax.swing.JButton jBotaoAlterar1;
    private javax.swing.JButton jBotaoAlterar2;
    private javax.swing.JButton jBotaoArquivo;
    private javax.swing.JButton jBotaoExcluir1;
    private javax.swing.JButton jBotaoExcluir2;
    private javax.swing.JButton jBotaoSalvaTudo;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPainel1;
    private javax.swing.JPanel jPainel2;
    private javax.swing.JPanel jPainelEntrada;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextoAdicionar1;
    private javax.swing.JTextField jTextoAdicionar2;
    private javax.swing.JTextField jTextoCaminhoArquivo;
    // End of variables declaration//GEN-END:variables
}
